### ISSUE TITLE
Add "disabled" attribute

### ISSUE THREAD

**Issue by Flet** [feross/standard-packages#1]
Should we also add an attribute to indicate if a repository is disabled? It may be a bit cleaner to do this instead of commenting them out (which is a pattern followed by standard/standard-engine). Maybe add a `disabledReason` attribute as well?

``` json
{
    "name": "funky-repo",
    "repo": "https://github.com/someone-cool/funky-repo",
    "disabled": true,
    "disabledReason": "has not updated to meet some-new-rule"
  },
```

**Comment by feross** [comment]
Yeah, this is a good idea. I just did this, except I combined the two into one `disable` property. If it's truthy, then it'll be disabled in the tests. :+1:

**Comment by Flet** [comment]
Perfect! Thanks!
