### ISSUE TITLE
Tooling/Script for discovering new standard packages

### ISSUE THREAD

**Issue by Flet** [feross/standard-packages#2]
Hey @feross do you have some script or set of steps you use to discover new packages using `standard`?

It may be useful to document those steps and possibly automate it if its not been done.

**Comment by feross** [comment]
Yeah, I should commit that code to this repo. I have it on my other laptop (which is currently broken). I will repair it when I'm back in the states (soon) and push it here :+1:

**Comment by feross** [comment]
The script is pushed to the repo now!
