### ISSUE TITLE
[IDEA] Add Travis Cron jobs

### ISSUE THREAD

**Issue by gbougakov** [feross/standard-packages#21]
To automatically update `all.json` you can make `npm run fetch && npm run update` a part of `npm test` and set up Travis CI to run `npm test` every day/week/month [like so](https://docs.travis-ci.com/user/cron-jobs/).

**Comment by feross** [comment]
This is a cool idea. Thanks for sharing it! But I don't really want to give Travis to have the ability to commit to my repos. So I'll just settle for updating this manually whenever I release a new `standard` version like I've been doing.
