### ISSUE TITLE
Add some metadata for each entry

### ISSUE THREAD

**Issue by Flet** [feross/standard-packages#3]
I was thinking of building a little script to pull the repositories tagline and maybe contributor(s)/homepage and adds them to the json. This would make it a bit more convenient to use for generating a web-friendly view.

Would you be opposed to having some additional metadata for each entry, @feross?

**Comment by feross** [comment]
Not opposed. :+1:

**Comment by feross** [comment]
Let me commit the scraping script I used (#2) since it should be easy to add the description in there.

**Comment by feross** [comment]
@Flet The script is committed now. If you want to modify it to include descriptions, feel free.

**Comment by Flet** [comment]
Thanks! What does `test.json` represent? I don't see it generated, and it seems to be just a subset of `standard.json`.. Is this just the target set of repos to use for `standard` tests?

**Comment by feross** [comment]
test.json is just the list of repos that used to be in clone.js. It's not
generated. I don't think it's necessary to add descriptions and other info
to test.json.

**Comment by feross** [comment]
This was fixed by @flet in https://github.com/feross/standard-packages/pull/4
